### ISSUE TITLE
contribute to this repo by adding new feature

### ISSUE THREAD

**Issue by royforlife** [vdtdg/dev-toolbox#9]
Hi vdtdg,

I'm really interested in this repo to build a lightweight developer toolbox(including many small useful tools).

I wonder if it's ok that I could contribute to this repo by adding new feature. I'm good at docker, k8s and full stack tech skills.

May I ask what's your next step about adding features so I can check what I can do for them(maybe new tools or dockerization)?

Best,
Roy

**Comment by vdtdg** [comment]
Hi Roy, we need more tools!

[If you take a look here](https://github.com/vdtdg/dev-toolbox?tab=readme-ov-file#next-features-to-be-developed-ordered-by-priority), you'll find a list of tools that would greatly benefit the toolbox. As you can see, some of them are already in progress, so pick from the rest!

You can also suggest new tools and develop them.

Good day,
Valérian

**Comment by vdtdg** [comment]
And after reflection @royforlife, a docker deployment would be nice to have!

**Comment by royforlife** [comment]
docker file added, working well in my laptop.
